### ISSUE TITLE
Smth broken while collecting advents at lenjaffe.com/AdventPlanet/2021

### ISSUE THREAD

**Issue by pheix** [vampirechicken/WWW-AdventCalendar-Magrathea#35]
http://www.lenjaffe.com/AdventPlanet/2021/index.html, seem smth is broken, 8th and 9th are blank:

![Снимок экрана от 2021-12-09 13-39-43](https://user-images.githubusercontent.com/6272762/145381518-ba2d2f6c-bd34-4c1c-9b56-bfdb68ecae93.png)

**Comment by vampirechicken** [comment]
Indeed. Thank you for bringing it to my attention.
Your truly left off a semicolon.

**Comment by vampirechicken** [comment]
Fixed
