### ISSUE TITLE
Make link to repo easier to find

### ISSUE THREAD

**Issue by oalders** [vampirechicken/WWW-AdventCalendar-Magrathea#40]
I had to Google to find this repo. If it's listed on the site, it escaped me. That could possibly be made more obvious.

**Comment by vampirechicken** [comment]
Why did you need the repo?

**Comment by oalders** [comment]
To ask if the Japanese advent calendar could be included.

**Comment by vampirechicken** [comment]
My email address is in the footer of almost every page of the website.

**Comment by oalders** [comment]
Feel free to close.

**Comment by vampirechicken** [comment]
This repo is linked to by both of my home pages.
